# Generated by Django 5.2.8 on 2025-11-18 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Название поставщика"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email поставщика"),
                ),
                (
                    "country",
                    models.CharField(max_length=100, verbose_name="Страна поставщика"),
                ),
                (
                    "city",
                    models.CharField(max_length=100, verbose_name="Город поставщика"),
                ),
                (
                    "street",
                    models.CharField(max_length=255, verbose_name="Улица поставщика"),
                ),
                (
                    "house_number",
                    models.CharField(
                        max_length=10, verbose_name="Номер дома поставщика"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NetworkNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("country", models.CharField(max_length=100, verbose_name="Страна")),
                ("city", models.CharField(max_length=100, verbose_name="Город")),
                ("street", models.CharField(max_length=255, verbose_name="Улица")),
                (
                    "house_number",
                    models.CharField(max_length=10, verbose_name="Номер дома"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=255, verbose_name="Название продукта"),
                ),
                (
                    "product_model",
                    models.CharField(max_length=255, verbose_name="Модель продукта"),
                ),
                (
                    "product_release_date",
                    models.DateField(verbose_name="Дата выпуска продукта"),
                ),
                (
                    "debt_to_supplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Задолженность перед поставщиком",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (0, "Завод"),
                            (1, "Розничная сеть"),
                            (2, "Индивидуальный предприниматель"),
                        ],
                        verbose_name="Уровень иерархии",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="network.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
        ),
    ]
